export interface Product {
  id: string;
  name: string;
  brand: string;
  price: number;
  originalPrice?: number;
  scent: string;
  category: string; // 'woody', 'floral', 'citrus', 'aquatic', 'oriental', 'powdery', 'luxury'
  categoryName: string; // '우디', '플로럴' 등
  stars: number;
  rating: number;
  reviewCount: number;
  badge?: 'BEST' | 'NEW' | 'SALE';
  imgBg?: string;
  imageType: 'santal' | 'blackopium' | 'libre' | 'bleu' | 'missdior' | 'aventus' | 'generic';
  description?: string;
  capacity?: string;
  imageUrl?: string;
}

export interface OrderItem {
  id: string;
  orderNo: string;
  productName: string;
  customerName: string;
  price: number;
  status: 'new' | 'prep' | 'ship' | 'done';
  statusLabel: string;
  date: string;
}

export interface ReportItem {
  id: string;
  title: string;
  reporter: string;
  time: string;
  type: 'review' | 'product' | 'inquiry';
  status: 'pending' | 'blinded' | 'resolved';
}

export interface VendorItem {
  id: string;
  name: string;
  email: string;
  description: string;
  status: 'pending' | 'approved' | 'rejected';
}

export const initialProducts: Product[] = [
  {
    id: 'p1',
    name: 'Amber Wood',
    brand: 'MODO',
    price: 210000,
    scent: '태운 나무 · 앰버 · 바닐라',
    category: 'woody',
    categoryName: 'MODO',
    stars: 5,
    rating: (Math.random() * 0.5 + 4.5).toFixed(1),
    reviewCount: 1020,
    badge: undefined,
    imageType: 'generic',
    description: '불에 탄 거친 나무토막과 그 사이에서 빛나는 영롱한 호박(Amber)의 조화.',
    capacity: '50ml',
    imageUrl: 'img/q1.png',
  },
  {
    id: 'p2',
    name: 'Marble Rose',
    brand: 'MODO',
    price: 210000,
    scent: '화이트 마블 · 핑크 로즈 · 머스크',
    category: 'floral',
    categoryName: 'MODO',
    stars: 5,
    rating: (Math.random() * 0.5 + 4.5).toFixed(1),
    reviewCount: 1686,
    badge: undefined,
    imageType: 'generic',
    description: '순백의 대리석 틈새로 피어나는 핑크빛 장미의 생명력을 담은 향기.',
    capacity: '50ml',
    imageUrl: 'img/q2.png',
  },
  {
    id: 'p3',
    name: 'Black Wax',
    brand: 'MODO',
    price: 210000,
    scent: '다크 레진 · 블랙 페퍼 · 패출리',
    category: 'oriental',
    categoryName: 'MODO',
    stars: 5,
    rating: (Math.random() * 0.5 + 4.5).toFixed(1),
    reviewCount: 313,
    badge: undefined,
    imageType: 'generic',
    description: '녹아내리는 짙은 검은색 왁스와 송진의 무게감이 느껴지는 깊고 관능적인 향.',
    capacity: '50ml',
    imageUrl: 'img/q3.png',
  },
  {
    id: 'p4',
    name: 'Crimson Flake',
    brand: 'MODO',
    price: 210000,
    scent: '레드 베리 · 사프란 · 골드 더스트',
    category: 'luxury',
    categoryName: 'MODO',
    stars: 5,
    rating: (Math.random() * 0.5 + 4.5).toFixed(1),
    reviewCount: 851,
    badge: 'BEST',
    imageType: 'generic',
    description: '붉은빛 캡 속에 박힌 황금 조각들처럼 화려하고 고급스러운 달콤함.',
    capacity: '50ml',
    imageUrl: 'img/q4.png',
  },
  {
    id: 'p5',
    name: 'Jade Stone',
    brand: 'MODO',
    price: 210000,
    scent: '그린 티 · 제이드 · 샌달우드',
    category: 'citrus',
    categoryName: 'MODO',
    stars: 5,
    rating: (Math.random() * 0.5 + 4.5).toFixed(1),
    reviewCount: 1740,
    badge: 'NEW',
    imageType: 'generic',
    description: '거친 바위 위에 얹힌 옥돌처럼 차갑고 맑은 자연의 숨결.',
    capacity: '50ml',
    imageUrl: 'img/q5.png',
  },
  {
    id: 'p6',
    name: 'Oceanic Blob',
    brand: 'MODO',
    price: 210000,
    scent: '아쿠아틱 해수 · 오조닉 노트 · 블루 마린',
    category: 'aquatic',
    categoryName: 'MODO',
    stars: 5,
    rating: (Math.random() * 0.5 + 4.5).toFixed(1),
    reviewCount: 1116,
    badge: undefined,
    imageType: 'generic',
    description: '심해의 푸른 바닷물을 유리에 가둔 듯한 청량하고 시원한 아쿠아틱 향.',
    capacity: '50ml',
    imageUrl: 'img/q6.png',
  },
  {
    id: 'p7',
    name: 'Golden Lavender',
    brand: 'MODO',
    price: 210000,
    scent: '허니 · 와일드 라벤더 · 클라리 세이지',
    category: 'floral',
    categoryName: 'MODO',
    stars: 5,
    rating: (Math.random() * 0.5 + 4.5).toFixed(1),
    reviewCount: 1144,
    badge: undefined,
    imageType: 'generic',
    description: '황금빛 꿀 속에 갇힌 보랏빛 라벤더의 달콤하고 편안한 허브 향.',
    capacity: '50ml',
    imageUrl: 'img/q7.png',
  },
  {
    id: 'p8',
    name: 'Magma Core',
    brand: 'MODO',
    price: 210000,
    scent: '스모키 우드 · 핫 스파이스 · 화산재',
    category: 'woody',
    categoryName: 'MODO',
    stars: 5,
    rating: (Math.random() * 0.5 + 4.5).toFixed(1),
    reviewCount: 1372,
    badge: 'BEST',
    imageType: 'generic',
    description: '갈라진 검은 돌 사이로 새어나오는 용암의 맹렬하고 스모키한 에너지.',
    capacity: '50ml',
    imageUrl: 'img/q8.png',
  },
  {
    id: 'p9',
    name: 'Silver Drip',
    brand: 'MODO',
    price: 210000,
    scent: '메탈릭 노트 · 아이리스 · 화이트 머스크',
    category: 'powdery',
    categoryName: 'MODO',
    stars: 5,
    rating: (Math.random() * 0.5 + 4.5).toFixed(1),
    reviewCount: 1858,
    badge: undefined,
    imageType: 'generic',
    description: '매끈한 검은 알 위로 흘러내리는 은빛 액체의 차갑고도 세련된 파우더리 향.',
    capacity: '50ml',
    imageUrl: 'img/q9.png',
  },
  {
    id: 'p10',
    name: 'Copper Stone',
    brand: 'MODO',
    price: 210000,
    scent: '코퍼 바이브 · 흙내음 · 베티버',
    category: 'woody',
    categoryName: 'MODO',
    stars: 5,
    rating: (Math.random() * 0.5 + 4.5).toFixed(1),
    reviewCount: 1088,
    badge: 'NEW',
    imageType: 'generic',
    description: '구리 띠를 두른 매끈한 조약돌처럼 단단하고 깊이 있는 우디와 어스(Earth) 향.',
    capacity: '50ml',
    imageUrl: 'img/q10.png',
  },
  {
    id: 'p11',
    name: 'Electric Violet',
    brand: 'MODO',
    price: 210000,
    scent: '바이올렛 리프 · 오존 · 짜릿한 스파이스',
    category: 'oriental',
    categoryName: 'MODO',
    stars: 5,
    rating: (Math.random() * 0.5 + 4.5).toFixed(1),
    reviewCount: 285,
    badge: undefined,
    imageType: 'generic',
    description: '얼음 속에 갇힌 보랏빛 번개처럼 강렬하고 스파이시한 일렉트릭 노트.',
    capacity: '50ml',
    imageUrl: 'img/q11.png',
  },
  {
    id: 'p12',
    name: 'Silver Leaf',
    brand: 'MODO',
    price: 210000,
    scent: '모닝 듀 · 은빛 잎사귀 · 시더우드',
    category: 'fresh',
    categoryName: 'MODO',
    stars: 5,
    rating: (Math.random() * 0.5 + 4.5).toFixed(1),
    reviewCount: 1629,
    badge: 'BEST',
    imageType: 'generic',
    description: '유리 돔 속 잎사귀 화석을 연상케 하는 맑고 투명한 이슬 맺힌 향.',
    capacity: '50ml',
    imageUrl: 'img/q12.png',
  },
  {
    id: 'p13',
    name: 'Monochrome Swirl',
    brand: 'MODO',
    price: 210000,
    scent: '밀크 폼 · 다크 초콜릿 · 통카빈',
    category: 'luxury',
    categoryName: 'MODO',
    stars: 5,
    rating: (Math.random() * 0.5 + 4.5).toFixed(1),
    reviewCount: 1258,
    badge: undefined,
    imageType: 'generic',
    description: '검은 연기와 하얀 연기가 뒤섞이는 듯한 관능적이고 부드러운 구르망 향.',
    capacity: '50ml',
    imageUrl: 'img/q13.png',
  },
  {
    id: 'p14',
    name: 'Desert Twig',
    brand: 'MODO',
    price: 210000,
    scent: '드라이 우드 · 샌드 · 오드(Oud)',
    category: 'woody',
    categoryName: 'MODO',
    stars: 5,
    rating: (Math.random() * 0.5 + 4.5).toFixed(1),
    reviewCount: 1392,
    badge: undefined,
    imageType: 'generic',
    description: '메마른 사막에서 찾아낸 마른 나뭇가지의 건조하고 우아한 나무 향.',
    capacity: '50ml',
    imageUrl: 'img/q14.png',
  },
  {
    id: 'p15',
    name: 'Toxic Marble',
    brand: 'MODO',
    price: 210000,
    scent: '네온 그린 앱시스 · 갈바눔 · 오크모스',
    category: 'citrus',
    categoryName: 'MODO',
    stars: 5,
    rating: (Math.random() * 0.5 + 4.5).toFixed(1),
    reviewCount: 2051,
    badge: 'NEW',
    imageType: 'generic',
    description: '순백의 대리석 틈새로 새어나오는 독성 있는 초록빛의 톡 쏘는 생명력.',
    capacity: '50ml',
    imageUrl: 'img/q15.png',
  },
  {
    id: 'p16',
    name: 'Purple Haze',
    brand: 'MODO',
    price: 210000,
    scent: '다크 플럼 · 인센스 · 앰버그리스',
    category: 'oriental',
    categoryName: 'MODO',
    stars: 5,
    rating: (Math.random() * 0.5 + 4.5).toFixed(1),
    reviewCount: 123,
    badge: 'BEST',
    imageType: 'generic',
    description: '유리 돔 속을 맴도는 보랏빛 연기처럼 몽환적이고 스모키한 분위기.',
    capacity: '50ml',
    imageUrl: 'img/q16.png',
  },
  {
    id: 'p17',
    name: 'Frost Crystal',
    brand: 'MODO',
    price: 210000,
    scent: '아이스 노트 · 민트 · 유칼립투스',
    category: 'fresh',
    categoryName: 'MODO',
    stars: 5,
    rating: (Math.random() * 0.5 + 4.5).toFixed(1),
    reviewCount: 675,
    badge: undefined,
    imageType: 'generic',
    description: '서리가 내린 차가운 얼음 결정체처럼 코끝을 스치는 극강의 상쾌함.',
    capacity: '50ml',
    imageUrl: 'img/q17.png',
  },
  {
    id: 'p18',
    name: 'Midnight Onyx',
    brand: 'MODO',
    price: 210000,
    scent: '블랙 트러플 · 오키드 · 다크 우드',
    category: 'luxury',
    categoryName: 'MODO',
    stars: 5,
    rating: (Math.random() * 0.5 + 4.5).toFixed(1),
    reviewCount: 1202,
    badge: undefined,
    imageType: 'generic',
    description: '자정의 오닉스 보석처럼 깊고 어두운 밤의 미스터리를 간직한 묵직한 향.',
    capacity: '50ml',
    imageUrl: 'img/q20.png',
  },
  {
    id: 'p19',
    name: 'Emerald Glass',
    brand: 'MODO',
    price: 210000,
    scent: '베르가못 · 무화과 잎 · 샌달우드',
    category: 'citrus',
    categoryName: 'MODO',
    stars: 5,
    rating: (Math.random() * 0.5 + 4.5).toFixed(1),
    reviewCount: 1732,
    badge: undefined,
    imageType: 'generic',
    description: '에메랄드빛 유리 공예품처럼 영롱하고 싱그러운 시트러스와 그리너리.',
    capacity: '50ml',
    imageUrl: 'img/q21.png',
  },
  {
    id: 'p20',
    name: 'Pearl Shimmer',
    brand: 'MODO',
    price: 210000,
    scent: '화이트 플로럴 · 알데하이드 · 머스크',
    category: 'powdery',
    categoryName: 'MODO',
    stars: 5,
    rating: (Math.random() * 0.5 + 4.5).toFixed(1),
    reviewCount: 590,
    badge: 'BEST',
    imageType: 'generic',
    description: '은은하게 빛나는 진주의 광택처럼 부드럽고 우아한 파우더리 플로럴.',
    capacity: '50ml',
    imageUrl: 'img/q22.png',
  },

  {
    id: 'p23',
    name: 'Delulu',
    brand: 'MODO',
    price: 172000,
    scent: 'Extrait de parfum',
    category: 'woody',
    categoryName: 'MODO',
    stars: 5,
    rating: 4.9,
    reviewCount: 300,
    imageType: 'generic',
    description: 'A fascinating blend of surreal and enchanting notes.',
    capacity: '50ml',
    imageUrl: 'img/z1.png',
  },
  {
    id: 'p24',
    name: 'Naked Dance',
    brand: 'MODO',
    price: 172000,
    scent: 'Extrait de parfum',
    category: 'floral',
    categoryName: 'MODO',
    stars: 5,
    rating: 4.8,
    reviewCount: 250,
    imageType: 'generic',
    description: 'An uninhibited, pure and natural floral expression.',
    capacity: '50ml',
    imageUrl: 'img/z2.png',
  },
  {
    id: 'p25',
    name: 'Dead Air',
    brand: 'MODO',
    price: 172500,
    scent: 'Extrait de parfum',
    category: 'oriental',
    categoryName: 'MODO',
    stars: 5,
    rating: 4.9,
    reviewCount: 420,
    imageType: 'generic',
    description: 'A deep, silent and powerful essence of the void.',
    capacity: '50ml',
    imageUrl: 'img/z3.png',
  },
  {
    id: 'p26',
    name: 'Phantom',
    brand: 'MODO',
    price: 185000,
    scent: 'Extrait de parfum',
    category: 'oriental',
    categoryName: 'MODO',
    stars: 5,
    rating: 5.0,
    reviewCount: 512,
    imageType: 'generic',
    description: 'An ethereal scent that captures the essence of mystery and elegance.',
    capacity: '50ml',
    imageUrl: 'img/z4.png',
  }
];

export const initialOrders: OrderItem[] = [
  {
    id: 'o1',
    orderNo: 'SA-2025-11284',
    productName: 'Santal 33 · 100ml',
    customerName: '김지현',
    price: 248000,
    status: 'new',
    statusLabel: '신규주문',
    date: '2026-05-27',
  },
  {
    id: 'o2',
    orderNo: 'SA-2025-11283',
    productName: 'Rose 31 · 50ml',
    customerName: '이민준',
    price: 168000,
    status: 'prep',
    statusLabel: '배송준비',
    date: '2026-05-26',
  },
  {
    id: 'o3',
    orderNo: 'SA-2025-11280',
    productName: 'Another 13 · 100ml',
    customerName: '박소연',
    price: 224000,
    status: 'ship',
    statusLabel: '배송중',
    date: '2026-05-25',
  },
  {
    id: 'o4',
    orderNo: 'SA-2025-11275',
    productName: 'Noir 29 · 100ml',
    customerName: '최준혁',
    price: 198000,
    status: 'done',
    statusLabel: '배송완료',
    date: '2026-05-24',
  },
];

export const initialReports: ReportItem[] = [
  {
    id: 'r1',
    title: '허위 리뷰 신고 — Aventus 상품',
    reporter: 'user_4821',
    time: '3분 전',
    type: 'review',
    status: 'pending',
  },
  {
    id: 'r2',
    title: '위조품 의심 신고 — Black Opium 50ml',
    reporter: 'user_2094',
    time: '17분 전',
    type: 'product',
    status: 'pending',
  },
  {
    id: 'r3',
    title: '욕설 포함 리뷰 신고 — Santal 33',
    reporter: 'user_5510',
    time: '42분 전',
    type: 'review',
    status: 'pending',
  },
  {
    id: 'r4',
    title: '스팸 리뷰 의심 — Miss Dior',
    reporter: 'user_3871',
    time: '1시간 전',
    type: 'review',
    status: 'pending',
  },
];

export const initialVendors: VendorItem[] = [
  {
    id: 'v1',
    name: '나이스 퍼퓸 (주)',
    email: 'contact@niceperfume.kr',
    description: '수입 향수 전문 디스트리뷰터',
    status: 'pending',
  },
  {
    id: 'v2',
    name: '향기로운 사람들',
    email: 'hello@scentpeople.co',
    description: '국내 디자이너 프래그런스 브랜드',
    status: 'pending',
  },
  {
    id: 'v3',
    name: 'Parfum Studio Co.',
    email: 'studio@parfum.kr',
    description: '천연 아로마 독립 향수 아틀리에',
    status: 'pending',
  },
  {
    id: 'v4',
    name: 'Niche Fragrance KR',
    email: 'info@nichefragrance.kr',
    description: '유럽 희귀 니치 향수 수입사',
    status: 'pending',
  },
];
